# Generated by Django 4.1.1 on 2022-11-22 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cac', '0002_docenteabs_estudianteabs_personam_docentem_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CursoM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('descripcion', models.TextField(null=True, verbose_name='Descripcion')),
                ('fecha_inicio', models.DateField(default=None, null=True, verbose_name='Fecha de inicio')),
                ('portada', models.ImageField(null=True, upload_to='imagenes/', verbose_name='Portada')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cac.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('nombre_slug', models.SlugField(max_length=100, verbose_name='Nombre Slug')),
                ('anio', models.IntegerField(verbose_name='Año')),
                ('descripcion', models.TextField(null=True, verbose_name='Descripcion')),
                ('url', models.URLField(max_length=100, verbose_name='Url')),
                ('portada', models.ImageField(null=True, upload_to='imagenes/proyecto/', verbose_name='Portada')),
            ],
        ),
        migrations.DeleteModel(
            name='DocenteAbs',
        ),
        migrations.RemoveField(
            model_name='estudiante',
            name='persona',
        ),
        migrations.DeleteModel(
            name='EstudianteAbs',
        ),
        migrations.AddField(
            model_name='curso',
            name='fecha_inicio',
            field=models.DateField(default=None, null=True, verbose_name='Fecha de inicio'),
        ),
        migrations.AddField(
            model_name='curso',
            name='portada',
            field=models.ImageField(null=True, upload_to='imagenes/', verbose_name='Portada'),
        ),
        migrations.AddField(
            model_name='estudiantem',
            name='baja',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='curso',
            name='estudiantes',
            field=models.ManyToManyField(through='cac.Inscripcion', to='cac.estudiantem'),
        ),
        migrations.AlterField(
            model_name='inscripcion',
            name='estudiante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cac.estudiantem'),
        ),
        migrations.DeleteModel(
            name='Estudiante',
        ),
        migrations.DeleteModel(
            name='Persona',
        ),
        migrations.AddField(
            model_name='proyecto',
            name='estudiante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cac.estudiantem'),
        ),
        migrations.AddField(
            model_name='cursom',
            name='estudiantes',
            field=models.ManyToManyField(to='cac.estudiantem'),
        ),
    ]
